dist: trusty
sudo: required
language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
before-install:
- pip install --no-binary=:all: numpy
- pip3 install --no-binary=:all: numpy
before-script:
- bash -x mnist/MNIST_data/download_mnist.sh
script:
- bash -x test/test_builds.sh
