dist: trusty
sudo: required
language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6
before-script:
- bash -x mnist/MNIST_data/download_mnist.sh
script:
- bash -x test/test_builds.sh
